name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.9
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git
publish_to: none

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.5.1
  shimmer: ^3.0.0
  # image_crop: ^0.4.1
  camera:
    git: https://github.com/kumsumit/camera.git
  image: ^4.3.0
  video_player:
    git: https://github.com/kumsumit/video_player.git
  image_picker:
    git: https://github.com/kumsumit/image_picker.git 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
